name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd ${{ secrets.APP_PATH }}

            echo "📥 Pull latest code"
            git pull origin main

            echo "📦 Install dependencies"
            bun install

            echo "🎨 Build frontend"
            cd packages/client
            bun run build
            cd ../..

            echo "🚀 Reload backend"
            pm2 reload ragify-api --update-env

            echo "✅ Deployment finished ✅ "

