name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 120s
          command_timeout: 20m
          script_stop: true
          debug: true
          script: |
            whoami
            hostname
            pwd

            cd ${{ secrets.APP_PATH }}

            git fetch origin
            git reset --hard origin/master

            bun install

            cd packages/client
            bun run build
            cd ../..

            echo "🚀 Reload backend"
            pm2 reload ragify-api --update-env

            echo "✅ Deployment finished ✅ "